version: '3.1'

services:

  postgres:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user_app
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
